substitutions:
  BLE_library: "https://github.com/s-gritsch/tesla-ble.git"
  tesla_ble_component: "github://s-gritsch/esphome-tesla-ble"
  ble_presence_timeout: 30s
  ble_components: [tesla_ble_vehicle, tesla_ble_listener]

esphome:
  libraries:
    - TeslaBLE=${BLE_library}

external_components:
  - source: $tesla_ble_component
    components: $ble_components

logger:
  level: INFO

api:
  homeassistant_services: true
